svg_icons:
  default: "square"
  type: "list"
  list_type: "compact"
extend_content_security_policy:
  type: list
  default: "script_src: https://cdnjs.cloudflare.com/ajax/libs/rough.js/3.1.0/rough.js"
